spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stylist_ai
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false